### ISSUE TITLE
When behind a TLS inspection proxy connections fails due to certificate issue

### ISSUE THREAD

**Issue by enemarke** [etnetera/owasp-dependency-check#10]
When behind a TLS inspection proxy connections fails due to certificate issue

```
owasp-dependency-check: No Dependency-Check Core executable found. Downloading into: xxx
(node:4592) UnhandledPromiseRejectionWarning: Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1514:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:708:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

How do I get it to trust the root certificate used by the proxy?

**Comment by centi** [comment]
This is not an issue with this package but rather with your system configuration. Did you try to search for the error? Try: https://github.com/nodejs/help/issues/979
